# Generated by Django 2.2.3 on 2019-11-14 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='company_name',
            field=models.CharField(default='', help_text='The name of the company', max_length=200),
        ),
    ]
