# Generated by Django 2.2.3 on 2019-11-15 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20191114_2117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='additional',
            field=models.CharField(max_length=200, verbose_name='EDRPOU code, HQ address, corporate phone number, corporate email address'),
        ),
        migrations.AlterField(
            model_name='company',
            name='website',
            field=models.URLField(verbose_name='Company Website'),
        ),
    ]
