# Generated by Django 2.2.3 on 2019-11-15 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20191116_0030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='region',
            field=models.CharField(blank=True, max_length=200, verbose_name='Region of registration of copyright, №, name TM'),
        ),
    ]
