# Generated by Django 2.2.3 on 2019-11-15 23:35

from django.db import migrations, models
import lawyerd.users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20191116_0031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='document_right',
            field=models.FileField(null=True, upload_to=lawyerd.users.models.company_get_file_path, verbose_name='Confirmation of rights to TM (PDF file with WIPO) '),
        ),
    ]
