# Generated by Django 2.2.3 on 2019-11-17 18:49

from django.db import migrations, models
import lawyerd.users.models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20191116_0135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='document',
            field=models.FileField(null=True, upload_to=lawyerd.users.models.company_get_file_path, verbose_name='Confirmation of the possibility of representing interests'),
        ),
        migrations.AlterField(
            model_name='company',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Representative telephone number'),
        ),
    ]
