# Generated by Django 2.2.7 on 2020-07-01 21:05

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20191117_2049'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='address',
        ),
        migrations.AddField(
            model_name='company',
            name='address_city',
            field=models.CharField(default='unknown', max_length=200, verbose_name='City'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='address_country',
            field=django_countries.fields.CountryField(default='US', max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='address_state',
            field=models.CharField(default='unknown', max_length=200, verbose_name='State/Province'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='address_street',
            field=models.CharField(default='unknown', max_length=200, verbose_name='Street Address:'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='address_zip',
            field=models.CharField(default='unknown', max_length=200, verbose_name='ZIP/Postal Code'),
            preserve_default=False,
        ),
    ]
