# Generated by Django 2.2.7 on 2020-08-13 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20200701_2305'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='terms',
            field=models.URLField(blank=True, verbose_name='Terms'),
        ),
        migrations.AlterField(
            model_name='company',
            name='address_street',
            field=models.CharField(max_length=200, verbose_name='Street Address'),
        ),
    ]
