# Generated by Django 2.2.7 on 2021-03-09 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20200813_0627'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='redirected_email',
            field=models.EmailField(default='', max_length=254, verbose_name='Redirect all emails to'),
        ),
    ]
