# Generated by Django 2.2.7 on 2021-03-10 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_user_redirected_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='redirected_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Redirect all emails to'),
        ),
    ]
