# Generated by Django 2.2.3 on 2019-11-17 18:49

from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='document',
            field=models.FileField(null=True, upload_to=products.models.product_get_file_path, validators=[products.models.validate_product_file_extension], verbose_name='Confirmation of the rights to TM (PDF  file with WIPO)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='document_file_name',
            field=models.CharField(max_length=200, verbose_name='Document file name'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=200, verbose_name='The name of the product'),
        ),
    ]
