# Generated by Django 2.2.7 on 2021-03-09 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_product_itype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='itype',
            field=models.IntegerField(choices=[(0, 'Game'), (1, 'Software'), (2, 'Photo'), (3, 'Picture'), (4, 'Course')], db_index=True, default=0, help_text='product type', verbose_name='Type of product'),
        ),
    ]
