# Generated by Django 2.2.3 on 2019-11-07 00:22

import complaint.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('query', models.CharField(help_text='Search query', max_length=200)),
                ('query_url', models.BooleanField(db_index=True, default=True, help_text='URL')),
                ('email', models.EmailField(help_text='Email to send abuse', max_length=254, null=True)),
                ('site_count', models.PositiveIntegerField(default=1, help_text='Count', validators=[django.core.validators.MinValueValidator(1)])),
                ('status', models.IntegerField(choices=[(0, 'waiting'), (1, 'processing'), (2, 'complete'), (3, 'cancelled'), (4, 'stopped')], db_index=True, default=0, help_text='Status')),
            ],
            options={
                'db_table': 'complaints',
            },
        ),
        migrations.CreateModel(
            name='ComplaintDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('site', models.CharField(help_text='Complaint URL', max_length=255, null=True)),
                ('hosting', models.CharField(help_text='Complaint hosting', max_length=255, null=True)),
                ('email', models.EmailField(help_text='Email', max_length=255, null=True)),
                ('screenshot', models.ImageField(blank=True, help_text='Screenshot', null=True, upload_to=complaint.models.complaint_details_get_file_path)),
                ('status', models.SmallIntegerField(choices=[(0, 'waiting'), (1, 'ok'), (2, 'error')], db_index=True, default=0, help_text='Status')),
                ('site_order', models.ForeignKey(help_text='Order', on_delete=django.db.models.deletion.CASCADE, to='complaint.Complaint')),
            ],
            options={
                'db_table': 'complaint_details',
            },
        ),
    ]
