# Generated by Django 2.2.3 on 2019-11-09 00:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('complaint', '0003_complaint_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaintdetail',
            name='site_order',
        ),
        migrations.AddField(
            model_name='complaintdetail',
            name='complaint',
            field=models.ForeignKey(default=1, help_text='Complaint', on_delete=django.db.models.deletion.CASCADE, to='complaint.Complaint'),
            preserve_default=False,
        ),
    ]
