# Generated by Django 2.2.7 on 2019-11-20 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('complaint', '0004_auto_20191109_0243'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint',
            name='query_url',
        ),
    ]
