# Generated by Django 2.2.7 on 2019-11-21 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaint', '0005_remove_complaint_query_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint',
            name='query',
        ),
        migrations.AddField(
            model_name='complaint',
            name='search_text',
            field=models.CharField(default='', help_text='Search text', max_length=200),
        ),
    ]
