# Generated by Django 2.2.7 on 2019-11-21 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaint', '0006_auto_20191121_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='email',
            field=models.EmailField(default='', help_text='Email to send abuse', max_length=254, null=True),
        ),
    ]
