# Generated by Django 2.2.7 on 2019-11-23 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaint', '0007_auto_20191121_1604'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='finished',
            field=models.DateField(help_text='Finish task Datetime ', null=True),
        ),
    ]
