# Generated by Django 2.2.7 on 2019-11-25 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaint', '0008_complaint_finished'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='finished',
            field=models.DateTimeField(help_text='Finish task Datetime ', null=True),
        ),
    ]
