# Generated by Django 2.2.7 on 2020-08-13 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaint', '0009_auto_20191125_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='status',
            field=models.IntegerField(choices=[(0, 'waiting'), (1, 'processing'), (2, 'ok'), (3, 'cancelled'), (4, 'stopped'), (5, 'error')], db_index=True, default=0, help_text='Status'),
        ),
        migrations.AlterField(
            model_name='complaintdetail',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'waiting'), (1, 'processing'), (2, 'ok'), (3, 'cancelled'), (4, 'stopped'), (5, 'error')], db_index=True, default=0, help_text='Status'),
        ),
    ]
