# Generated by Django 2.2.7 on 2021-02-23 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaint', '0010_auto_20200813_0627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='status',
            field=models.IntegerField(choices=[(0, 'waiting'), (1, 'processing'), (2, 'ok'), (3, 'cancelled'), (5, 'error')], db_index=True, default=0, help_text='Status'),
        ),
        migrations.AlterField(
            model_name='complaintdetail',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'waiting'), (1, 'processing'), (2, 'ok'), (3, 'cancelled'), (5, 'error')], db_index=True, default=0, help_text='Status'),
        ),
    ]
