# Generated by Django 2.2.19 on 2021-03-15 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaint', '0012_auto_20210309_2208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaintdetail',
            name='site',
            field=models.CharField(help_text='Complaint URL', max_length=1000, null=True),
        ),
    ]
