# Generated by Django 2.2.19 on 2021-03-18 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaint', '0013_auto_20210315_1427'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaintdetail',
            name='template_name',
            field=models.CharField(help_text='Template name', max_length=255, null=True),
        ),
    ]
